added reportporta testresult collector.
Hygieia/hygieia-codequality-reportportal-collector pull request #1
Opened 2019-06-13 05:31 UTC by gopiprasanthpotipireddy

the first version of reportportal testresults collector without unit tests.

2019-06-13 05:32 UTC, gopiprasanthpotipireddy commented
@rvema can you review it now.

2019-06-17 13:08 UTC, rvema requested changes
please look into the review comments and address them. Do ping me on gitter in case you need additional information

2019-06-17 13:08 UTC, rvema commented on application.properties
> +		dbpassword=dbpassword
please refrain from storing username and password in the property files in github. Please point to the documentation mentioning that this needs to be updated.

2019-06-17 13:08 UTC, rvema commented on pom.xml
> +    <relativePath>../../..</relativePath>
please remove this dependency on relativePath. Every collector should be on its own.

2019-06-17 13:08 UTC, rvema commented on src/main/java/com/capitalone/dashboard/collector/DefaultReportPortalClient.java
> +                //project.setInstanceUrl(instanceUrl);
please remove the commented code.

2019-06-17 13:08 UTC, rvema commented on src/main/java/com/capitalone/dashboard/collector/DefaultReportPortalClient.java
> +     		//step.setFailedTestStepCount((integer(executions,"failed")));
please remove the commented code.

2019-06-17 13:08 UTC, rvema commented on src/main/java/com/capitalone/dashboard/collector/ReportPortalCollectorTask.java
> +        //clean(collector, existingProjects);
please remove the commented lines of code.

2019-06-17 13:08 UTC, rvema commented on src/main/java/com/capitalone/dashboard/collector/ReportPortalSettings.java
> +	//private String instanceUrl;
please remove the commented line of code

2019-06-17 13:08 UTC, rvema commented on src/main/java/com/capitalone/dashboard/collector/RestOperationsSupplier.java
> +        requestFactory.setConnectTimeout(20000);
please have the timeout parameters configurable through the properties

2019-06-17 13:08 UTC, rvema commented on src/main/java/com/capitalone/dashboard/model/ReportPortalCollector.java
> +        //allOptions.put(ReportPortalProject.INSTANCE_URL,"" );
please remove the commented lines of code

2019-06-18 15:17 UTC, gopiprasanthpotipireddy reviewed
@rvema updated the changes. can you look into it now.

2019-06-19 02:35 UTC, rvema approved these changes
lgtm

2019-06-19 02:35 UTC, merged